# Generated by Django 5.0.7 on 2026-02-06 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_service_default_commission_percent'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Agendado'), ('CONFIRMED', 'Confirmado'), ('DONE', 'Atendido'), ('NO_SHOW', 'Faltou'), ('CANCELED', 'Cancelado')], default='SCHEDULED', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='customers.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='core.service')),
            ],
            options={
                'ordering': ['-start_at'],
                'indexes': [models.Index(fields=['barber', 'start_at'], name='scheduling__barber__13229f_idx'), models.Index(fields=['start_at'], name='scheduling__start_a_244e63_idx'), models.Index(fields=['status'], name='scheduling__status_1008cc_idx')],
            },
        ),
    ]
