# Generated by Django 5.0.7 on 2026-02-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='default_commission_percent',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
    ]
